name: Slack checker

on:
  schedule:
    - cron: "5 * * * *"

  workflow_dispatch:

jobs:
  slack-checker:
    # Cannot check the existence of secrets, so limiting to repository name to prevent all forks to run nightly.
    # See: https://github.com/actions/runner/issues/520
    if: ${{ github.repository == 'wagtail/slackchecker' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install requests
      - name: Test
        id: test
        continue-on-error: true
        run: |
          python .github/slackchecker.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: gautamkrishnar/keepalive-workflow@v1
